-- Base schema; for an existing project run migrations/002_security_multitenant.sql after this file.
create extension if not exists pgcrypto;
do $$ begin create type public.app_role as enum ('empresa','candidato','admin'); exception when duplicate_object then null; end $$;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,role public.app_role not null default 'candidato',full_name text not null,phone text,city text,state text default 'RS',created_at timestamptz not null default now());
create table if not exists public.companies(id uuid primary key default gen_random_uuid(),name text not null,cnpj text unique,city text not null,state text not null default 'RS',industry text,created_at timestamptz not null default now());
create table if not exists public.skills(id uuid primary key default gen_random_uuid(),name text not null unique,category text not null,parent_skill_id uuid references public.skills(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.candidate_profiles(profile_id uuid primary key references public.profiles(id) on delete cascade,years_experience numeric(5,1) not null default 0,desired_salary numeric(12,2),availability text,bio text,updated_at timestamptz not null default now());
create table if not exists public.candidate_skills(candidate_id uuid not null references public.candidate_profiles(profile_id) on delete cascade,skill_id uuid not null references public.skills(id) on delete cascade,proficiency smallint not null default 3 check(proficiency between 1 and 5),verified boolean not null default false,evidence_url text,years_experience numeric(5,1) not null default 0,primary key(candidate_id,skill_id));
create table if not exists public.jobs(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,title text not null,description text,city text not null,salary_min numeric(12,2),salary_max numeric(12,2),shift text,status text not null default 'aberta' check(status in ('aberta','fechada','pausada')),created_at timestamptz not null default now());
create table if not exists public.job_skills(job_id uuid not null references public.jobs(id) on delete cascade,skill_id uuid not null references public.skills(id) on delete cascade,required boolean not null default true,min_proficiency smallint not null default 3 check(min_proficiency between 1 and 5),weight numeric(6,3) not null default 1,primary key(job_id,skill_id));
create table if not exists public.matches(id uuid primary key default gen_random_uuid(),job_id uuid not null references public.jobs(id) on delete cascade,candidate_id uuid not null references public.candidate_profiles(profile_id) on delete cascade,score numeric(5,2) not null,reasons jsonb not null default '[]'::jsonb,gaps jsonb not null default '[]'::jsonb,created_at timestamptz not null default now(),unique(job_id,candidate_id));
create table if not exists public.applications(id uuid primary key default gen_random_uuid(),job_id uuid not null references public.jobs(id) on delete cascade,candidate_id uuid not null references public.candidate_profiles(profile_id) on delete cascade,status text not null default 'novo' check(status in ('novo','triagem','entrevista','aprovado','rejeitado','contratado')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(job_id,candidate_id));
create index if not exists idx_candidate_skills_skill on public.candidate_skills(skill_id);
create index if not exists idx_job_skills_skill on public.job_skills(skill_id);
create index if not exists idx_jobs_city_status on public.jobs(city,status);
create index if not exists idx_matches_job_score on public.matches(job_id,score desc);
alter table public.profiles enable row level security;alter table public.companies enable row level security;alter table public.skills enable row level security;alter table public.candidate_profiles enable row level security;alter table public.candidate_skills enable row level security;alter table public.jobs enable row level security;alter table public.job_skills enable row level security;alter table public.matches enable row level security;alter table public.applications enable row level security;
insert into public.skills(name,category) values('CNC','Usinagem'),('Metrologia','Usinagem'),('Desenho Técnico','Usinagem'),('Leitura de Instrumentos','Usinagem'),('Mecânica','Manutenção'),('Elétrica','Manutenção'),('CLP','Automação'),('Pneumática','Manutenção'),('MIG/MAG','Soldagem'),('TIG','Soldagem'),('Usinagem','Usinagem') on conflict(name) do nothing;
