-- TalentOS only. Occupations are a curated industrial list (not official CBO).
CREATE TABLE IF NOT EXISTS public.industrial_occupations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE CHECK (char_length(name) BETWEEN 2 AND 130),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.industrial_occupations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.industrial_occupations FROM PUBLIC;
GRANT SELECT ON public.industrial_occupations TO anon, authenticated;
DROP POLICY IF EXISTS "occupation_catalog_public_read" ON public.industrial_occupations;
CREATE POLICY "occupation_catalog_public_read" ON public.industrial_occupations FOR SELECT
TO anon, authenticated USING (active = true);

INSERT INTO public.industrial_occupations(name)
VALUES
  ('Almoxarife'),
  ('Analista de Controle de Qualidade'),
  ('Analista de Logística'),
  ('Analista de PCP'),
  ('Analista de Processos'),
  ('Aprendiz Industrial'),
  ('Auxiliar de Manutenção'),
  ('Auxiliar de Produção'),
  ('Caldeireiro'),
  ('Coordenador Industrial'),
  ('Desenhista Técnico Mecânico'),
  ('Eletricista Industrial'),
  ('Encarregado de Produção'),
  ('Engenheiro de Processos'),
  ('Engenheiro de Produção'),
  ('Engenheiro Eletricista'),
  ('Engenheiro Mecânico'),
  ('Estoquista'),
  ('Ferramenteiro'),
  ('Fresador Mecânico'),
  ('Gerente Industrial'),
  ('Inspetor de Qualidade'),
  ('Inspetor de Soldagem'),
  ('Instrumentista Industrial'),
  ('Líder de Produção'),
  ('Mecânico de Manutenção Industrial'),
  ('Mecânico Industrial'),
  ('Metrologista'),
  ('Montador Industrial'),
  ('Operador CNC'),
  ('Operador de Calandra'),
  ('Operador de Centro de Usinagem'),
  ('Operador de Empilhadeira'),
  ('Operador de Injetora'),
  ('Operador de Ponte Rolante'),
  ('Operador de Prensa'),
  ('Operador de Produção'),
  ('Operador de Torno Convencional'),
  ('Pintor Industrial'),
  ('Planejador de Manutenção'),
  ('Programador CNC'),
  ('Programador de CLP'),
  ('Projetista Mecânico'),
  ('Soldador'),
  ('Soldador MIG/MAG'),
  ('Soldador TIG'),
  ('Supervisor de Manutenção'),
  ('Supervisor de Produção'),
  ('Técnico de Automação Industrial'),
  ('Técnico de Manutenção'),
  ('Técnico de Qualidade'),
  ('Técnico de Segurança do Trabalho'),
  ('Técnico em Eletrotécnica'),
  ('Técnico em Mecânica'),
  ('Técnico em Mecatrônica'),
  ('Torneiro Mecânico')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.skills(name,category)
VALUES
  ('5S', 'Industrial'),
  ('Análise de Falhas', 'Industrial'),
  ('Automação Industrial', 'Industrial'),
  ('Caldeiraria', 'Industrial'),
  ('CLP', 'Industrial'),
  ('CNC', 'Industrial'),
  ('Comandos Elétricos', 'Industrial'),
  ('Controle de Qualidade', 'Industrial'),
  ('Controle Dimensional', 'Industrial'),
  ('Corte e Dobra', 'Industrial'),
  ('Desenho Técnico', 'Industrial'),
  ('Elétrica', 'Industrial'),
  ('Eletricidade Industrial', 'Industrial'),
  ('Eletropneumática', 'Industrial'),
  ('Equipamentos de Medição', 'Industrial'),
  ('FMEA', 'Industrial'),
  ('Fresamento', 'Industrial'),
  ('Gestão de Estoques', 'Industrial'),
  ('Hidráulica', 'Industrial'),
  ('Inspeção de Qualidade', 'Industrial'),
  ('Instrumentação Industrial', 'Industrial'),
  ('Interpretação de Desenho Técnico', 'Industrial'),
  ('ISO 9001', 'Industrial'),
  ('Lean Manufacturing', 'Industrial'),
  ('Leitura de Instrumentos', 'Industrial'),
  ('Liderança de Equipes', 'Industrial'),
  ('Manutenção Corretiva', 'Industrial'),
  ('Manutenção Preditiva', 'Industrial'),
  ('Manutenção Preventiva', 'Industrial'),
  ('Mecânica', 'Industrial'),
  ('Mecânica Industrial', 'Industrial'),
  ('Metrologia', 'Industrial'),
  ('MIG/MAG', 'Industrial'),
  ('Montagem Industrial', 'Industrial'),
  ('NR-10', 'Industrial'),
  ('NR-12', 'Industrial'),
  ('NR-33', 'Industrial'),
  ('NR-35', 'Industrial'),
  ('Operação de Empilhadeira', 'Industrial'),
  ('Operação de Máquinas', 'Industrial'),
  ('PCP', 'Industrial'),
  ('Pneumática', 'Industrial'),
  ('Programação CNC', 'Industrial'),
  ('Programação de CLP', 'Industrial'),
  ('Projetos Mecânicos', 'Industrial'),
  ('Qualidade Industrial', 'Industrial'),
  ('Segurança do Trabalho', 'Industrial'),
  ('Setup de Máquinas', 'Industrial'),
  ('Soldagem Industrial', 'Industrial'),
  ('SolidWorks', 'Industrial'),
  ('TIG', 'Industrial'),
  ('Torno CNC', 'Industrial'),
  ('Torno Convencional', 'Industrial'),
  ('Usinagem', 'Industrial'),
  ('WCM', 'Industrial')
ON CONFLICT (name) DO NOTHING;

ALTER TABLE public.candidate_profiles
  ADD COLUMN IF NOT EXISTS current_role_title text,
  ADD COLUMN IF NOT EXISTS desired_role_titles text[] NOT NULL DEFAULT '{}'::text[];

-- Preserve previous role, consent, resume, and skill-trust restrictions.
CREATE OR REPLACE FUNCTION public.save_candidate_passport(p_profile jsonb, p_skills jsonb, p_resume jsonb DEFAULT NULL::jsonb)
 RETURNS uuid
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare v_user uuid:=auth.uid(); v_resume uuid; v_row jsonb; v_existing public.candidate_skills;
 v_name text:=nullif(trim(p_profile->>'name'),''); v_city text:=nullif(trim(p_profile->>'city'),'');
begin
 if v_user is null or private.current_role() is distinct from 'candidato' then raise exception 'Somente candidatos podem salvar o próprio currículo'; end if;
 if v_name is null or v_city is null or nullif(trim(p_profile->>'role'),'') is null then raise exception 'Informe nome, função e cidade'; end if;
 if p_skills is null or jsonb_typeof(p_skills)<>'array' then raise exception 'Lista de habilidades inválida'; end if;
 if jsonb_array_length(p_skills)>150 then raise exception 'Limite de 150 habilidades'; end if;
 perform 1 from public.profiles where id=v_user for update;
 insert into public.candidate_profiles(profile_id,display_name,role_title,city,years_experience,desired_salary,bio,searchable,visibility_consent_at,consent_version)
 values(v_user,v_name,trim(p_profile->>'role'),v_city,greatest(0,coalesce((p_profile->>'years')::numeric,0)),
 greatest(0,coalesce((p_profile->>'salary')::numeric,0)),nullif(trim(p_profile->>'bio'),''),coalesce((p_profile->>'searchable')::boolean,false),
 case when coalesce((p_profile->>'searchable')::boolean,false) then now() end,
 case when coalesce((p_profile->>'searchable')::boolean,false) then 'v1' end)
 on conflict(profile_id) do update set display_name=excluded.display_name,role_title=excluded.role_title,city=excluded.city,
 years_experience=excluded.years_experience,desired_salary=excluded.desired_salary,bio=excluded.bio,
 searchable=excluded.searchable,visibility_consent_at=excluded.visibility_consent_at,consent_version=excluded.consent_version,updated_at=now();

 if p_profile ? 'desiredRoles' then
   if jsonb_typeof(p_profile->'desiredRoles') <> 'array'
      or jsonb_array_length(p_profile->'desiredRoles') > 8
      or exists (
        select 1 from jsonb_array_elements_text(p_profile->'desiredRoles') roles(role_name)
         where not exists (select 1 from public.industrial_occupations catalog where catalog.name = roles.role_name)
      )
   then raise exception 'Selecione até oito funções desejadas da lista industrial'; end if;
 end if;
 if p_profile ? 'currentRole' and nullif(trim(p_profile->>'currentRole'), '') is not null
    and trim(p_profile->>'currentRole') <> 'Desempregado'
    and not exists (
      select 1 from public.industrial_occupations catalog
       where catalog.name = trim(p_profile->>'currentRole')
    )
 then raise exception 'Selecione a função atual da lista industrial'; end if;
 update public.candidate_profiles
    set current_role_title = case when p_profile ? 'currentRole' then nullif(trim(p_profile->>'currentRole'), '') else current_role_title end,
        desired_role_titles = case when p_profile ? 'desiredRoles'
          then array(select distinct role_name from jsonb_array_elements_text(p_profile->'desiredRoles') x(role_name))
          else desired_role_titles end
  where profile_id = v_user;
 if p_resume is not null then
   if p_resume->>'mime_type' not in ('application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document')
    or coalesce((p_resume->>'file_size')::bigint,0) not between 1 and 10485760
    or split_part(p_resume->>'storage_path','/',1) is distinct from v_user::text
    or not exists(select 1 from storage.objects o where o.bucket_id='candidate-resumes' and o.name=p_resume->>'storage_path')
   then raise exception 'Arquivo de currículo inválido ou não pertence ao candidato'; end if;
   insert into public.candidate_resumes(candidate_id,storage_path,file_name,mime_type,file_size)
   values(v_user,p_resume->>'storage_path',p_resume->>'file_name',p_resume->>'mime_type',(p_resume->>'file_size')::bigint)
   on conflict(candidate_id) do update set storage_path=excluded.storage_path,file_name=excluded.file_name,mime_type=excluded.mime_type,file_size=excluded.file_size,updated_at=now()
   returning id into v_resume;
 end if;
 if p_profile ? 'preferredShifts' then
   insert into public.talent_preferences(candidate_id,preferred_shifts)
   values(v_user,array(select jsonb_array_elements_text(p_profile->'preferredShifts')))
   on conflict(candidate_id) do update set preferred_shifts=excluded.preferred_shifts;
 end if;
 for v_row in select value from jsonb_array_elements(p_skills) loop
   if v_row->>'source_type' is null or v_row->>'source_type' not in ('manual','curriculo') then raise exception 'Origem de habilidade inválida'; end if;
   if v_row->>'source_type'='curriculo' and v_resume is null then raise exception 'Currículo não enviado'; end if;
   select * into v_existing from public.candidate_skills where candidate_id=v_user and skill_id=(v_row->>'skill_id')::uuid;
   if found then
     -- Editing the resume never downgrades established proficiency, provenance or verification.
     update public.candidate_skills set years_experience=greatest(years_experience,coalesce((v_row->>'years_experience')::numeric,0))
     where candidate_id=v_user and skill_id=(v_row->>'skill_id')::uuid;
   else
     insert into public.candidate_skills(candidate_id,skill_id,proficiency,verified,years_experience,source_type,source_confidence,source_excerpt,source_resume_id)
     values(v_user,(v_row->>'skill_id')::uuid,case when v_row->>'source_type'='curriculo' then 1 else 3 end,false,
     greatest(0,coalesce((v_row->>'years_experience')::numeric,0)),v_row->>'source_type',
     case when v_row->>'source_type'='curriculo' then least(1,greatest(0,coalesce((v_row->>'source_confidence')::numeric,0.6))) end,
     case when v_row->>'source_type'='curriculo' then left(v_row->>'source_excerpt',500) end,
     case when v_row->>'source_type'='curriculo' then v_resume end);
   end if;
 end loop;
 delete from public.candidate_skills cs where cs.candidate_id=v_user and not cs.verified and cs.source_type in ('manual','curriculo')
 and not exists(select 1 from jsonb_array_elements(p_skills) row where (row->>'skill_id')::uuid=cs.skill_id);
 perform public.log_audit_event('candidate_passport_saved','candidate_profiles',v_user,jsonb_build_object('skills_count',jsonb_array_length(p_skills),'resume_changed',p_resume is not null));
 return v_resume;
end $function$

